job/urls.py
from django.urls import path , include
 
from . import views
from . import api 


app_name='job'

urlpatterns = [
    path('',views.job_list,name='job_list'),
    path('add',views.add_job,name='add_job'),
    path('<str:slug>',views.job_detail,name='job_detail'),
    # path('api/jobs',api.job_list_api,name='job_list_api'),
    # path('api/jobs/<int:id>',api.job_detail_api,name='job_detail_api'),
    
    #class based view 
    path('api/v2/jobs',api.JobListApi.as_view(),name='job_list_api'),
    path('api/v2/jobs/<int:id>',api.JobDetail.as_view(),name='jobDetail'),
    
]

project/urls.py
from argparse import Namespace
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
    path('jobs/',include('job.urls',namespace='jobs')),
    path('contact-us/',include('contact.urls',namespace='contacts')),
    # path('home/',include('home.urls',namespace='home')),
    path('api-auth/', include('rest_framework.urls'))
    
]

urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

job/models.py
from email.policy import default
from random import choices
from django.db import models
from django.utils.text import slugify
from sqlalchemy import ForeignKey
from django.contrib.auth.models import User


JOB_TYPE = (
    ('Full Time','Full Time'),
    ('Part Time', 'Part Time'),
)

def image_upload(instance, filename):
    imagename , extention = filename.split(".")
    return "jobs/%s.%s"%(instance.id,extention)

# Create your models here.
class job(models.Model):
    owner = models.ForeignKey(User,related_name="job_owner",on_delete=models.CASCADE)
    title = models.CharField(max_length=100)  # column
    job_type = models.CharField(max_length=15,choices=JOB_TYPE)
    description = models.TextField(max_length=1000)
    published_at = models.DateTimeField(auto_now=True)
    Vacancy = models.IntegerField(default=1)
    salary = models.IntegerField(default=0)
    Image = models.ImageField(upload_to=image_upload)
    experience = models.IntegerField(default=1)
    category = models.ForeignKey('Category',on_delete=models.CASCADE)
    slug = models.SlugField(blank=True, null=True)
   
    def __str__(self) :
        return self.title   # return title in job admin panel
    
    def save(self,*args,**kwargs):
        self.slug = slugify(self.title)
        super(job,self).save(*args,**kwargs)
    
    

class Category(models.Model):
    name = models.CharField(max_length=25)
    
    def __str__(self):
        return self.name
 
 
 
    
class Apply(models.Model):
    job = models.ForeignKey(job,related_name='apply_job',on_delete=models.CASCADE) 
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=100)
    website = models.URLField()
    upload_cv = models.FileField(upload_to='apply/')
    cover_letter = models.TextField(max_length=500)
    created_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.name

job/views.py
from audioop import reverse
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from .models import job
from django.shortcuts import render
from django.core.paginator import Paginator
from .form import ApplyForm,AddNewJob
from django.urls import reverse
from .filters import JobFilter


# Create your views here.

def job_list(request):
    job_list = job.objects.all()
    #filters
    my_filter = JobFilter(request.GET,queryset=job_list)
    job_list = my_filter.qs
    
    paginator = Paginator(job_list, 3)   # 1 job per page
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {"jobs": page_obj,'my_filter':my_filter}  # Template Name
    return render(request,'job/job_list.html',context)



def job_detail(request, slug):
    job_detail = job.objects.get(slug=slug)
    
    if request.method == "POST":
        form = ApplyForm(request.POST , request.FILES)
        if form.is_valid():
            my_form = form.save(commit=False)
            my_form.job = job_detail
            my_form.save()
            
    
    else:
        form = ApplyForm()
        
    context = {"job": job_detail,"form": form}
    return render(request, 'job/job_detail.html',context)

@login_required
def add_job(request):
    
    if request.method=="POST":
        form = AddNewJob(request.POST, request.FILES)
        if form.is_valid():
            my_form = form.save(commit=False)
            my_form.owner=request.user
            my_form.save()
            return redirect(reverse('jobs:job_list'))
    else:
        form = AddNewJob()
        
    context = {"form": form}
    return render(request, 'job/add_job.html',context)

job/templates/job/add_job.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
        <!-- bradcam_area  -->
        
        <div class="bradcam_area bradcam_bg_1">
            <div class="container">
                <div class="row">
                    <div class="col-xl-12">
                        <div class="bradcam_text">
                            <h3>Post A New Job</h3>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--/ bradcam_area  -->
    
        <div class="job_details_area">
            <div class="container">
                <div class="row">
                    <div class="col-lg-10 mx-auto">
                    
                        <div class="apply_job_form white-bg">
                            <h4>Post New job</h4>
                            <form action="#" method = "POST" enctype="multipart/form-data">
                                {% csrf_token %}
                                {% bootstrap_form form %}
                                {% buttons %}
                                    <button class="boxed-btn3 w-100" type="submit">Post Now</button>
                                {% endbuttons %}
                            
                            </form>
                        </div>
                    </div>
                    <div class="col-lg-4">
                    </div>
                </div>
            </div>
        </div>
    
{%endblock body%} 

job/templates/job/job_detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
        <!-- bradcam_area  -->
        
        <div class="bradcam_area bradcam_bg_1">
            <div class="container">
                <div class="row">
                    <div class="col-xl-12">
                        <div class="bradcam_text">
                            <h3>{{job}}</h3>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--/ bradcam_area  -->
    
        <div class="job_details_area">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8">
                        <div class="job_details_header">
                            <div class="single_jobs white-bg d-flex justify-content-between">
                                <div class="jobs_left d-flex align-items-center">
                                    <div class="thumb">
                                        <img src="img/svg_icon/1.svg" alt="">
                                    </div>
                                    <div class="jobs_conetent">
                                        <a href="#"><h4>{{job}}</h4></a>
                                        <div class="links_locat d-flex align-items-center">
                                            <div class="location">
                                                <p> <i class="fa fa-map-marker"></i> California, USA</p>
                                            </div>
                                            <div class="location">
                                                <p> <i class="fa fa-clock-o"></i> {{job.job_type}}</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="jobs_right">
                                    <div class="apply_now">
                                        <a class="heart_mark" href="#"> <i class="ti-heart"></i> </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="descript_wrap white-bg">
                            <div class="single_wrap">
                                <h4>Job description</h4>
                                <p>{{job.description}}</p>
                            </div>
                        </div>
                        <div class="apply_job_form white-bg">
                            <h4>Apply for the job</h4>
                            <form action="#" method = "POST" enctype="multipart/form-data">
                                {% csrf_token %}
                                {% bootstrap_form form %}
                                {% buttons %}
                                    <button class="boxed-btn3 w-100" type="submit">Apply Now</button>
                                {% endbuttons %}
                            
                            </form>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="job_sumary">
                            <div class="summery_header">
                                <h3>Job Summery</h3>
                            </div>
                            <div class="job_content">
                                <ul>
                                    <li>Published on: <span>{{job.published_at|date:'d M o'}}</span></li>
                                    <li>Vacancy: <span>{{job.Vacancy}} Position</span></li>
                                    <li>Salary: <span>{{job.salary}}</span></li>
                                    <li>Location: <span>California, USA</span></li>
                                    <li>Job Nature: <span> {{job.job_type}}</span></li>
                                </ul>
                            </div>
                        </div>
                        <div class="share_wrap d-flex">
                            <span>Share at:</span>
                            <ul>
                                <li><a href="#"> <i class="fa fa-facebook"></i></a> </li>
                                <li><a href="#"> <i class="fa fa-google-plus"></i></a> </li>
                                <li><a href="#"> <i class="fa fa-twitter"></i></a> </li>
                                <li><a href="#"> <i class="fa fa-envelope"></i></a> </li>
                            </ul>
                        </div>
                        <div class="job_location_wrap">
                            <div class="job_lok_inner">
                                <div id="map" style="height: 200px;"></div>
                                <script>
                                  function initMap() {
                                    var uluru = {lat: -25.363, lng: 131.044};
                                    var grayStyles = [
                                      {
                                        featureType: "all",
                                        stylers: [
                                          { saturation: -90 },
                                          { lightness: 50 }
                                        ]
                                      },
                                      {elementType: 'labels.text.fill', stylers: [{color: '#ccdee9'}]}
                                    ];
                                    var map = new google.maps.Map(document.getElementById('map'), {
                                      center: {lat: -31.197, lng: 150.744},
                                      zoom: 9,
                                      styles: grayStyles,
                                      scrollwheel:  false
                                    });
                                  }
                                  
                                </script>
                                <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDpfS1oRGreGSBU5HHjMmQ3o5NLw7VdJ6I&callback=initMap"></script>
                                
                              </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    
{%endblock body%} 

job/templates/job/job_list.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}

<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="bradcam_text">
                    <h3>{{jobs.count}}+ Jobs Available</h3>
                </div>
            </div>
        </div>
    </div>
</div>



<div class="job_listing_area plus_padding">
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <div class="job_filter white-bg">
                    <div class="form_inner white-bg">
                        <h3>Filter</h3>
                        <form method="GET">
                           {% bootstrap_form my_filter.form  %} 
                           <input type='submit' value='Search' class="boxed-btn3 w-100"> 
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-lg-9">
                <div class="recent_joblist_wrap">
                    <div class="recent_joblist white-bg ">
                        <div class="row align-items-center">
                            <div class="col-md-6">
                                <h4>Job Listing</h4>
                            </div>
                            <div class="col-md-6">
                            </div>
                        </div>
                    </div>
                </div>

                <div class="job_lists m-0">
                    <div class="row">
                        {% for job in  jobs %}
                        <div class="col-lg-12 col-md-12">
                            <div class="single_jobs white-bg d-flex justify-content-between">
                                <div class="jobs_left d-flex align-items-center">
                                    <div class="thumb">
                                        <img src="" alt="">
                                    </div>
                                    <div class="jobs_conetent">
                                        <a href="{% url 'job:job_detail' job.slug %}"><h4>{{job.title}}</h4></a>
                                        <div class="links_locat d-flex align-items-center">
                                            <div class="location">
                                                <p> <i class="fa fa-map-marker"></i> California, USA</p>
                                            </div>
                                            <div class="location">
                                                <p> <i class="fa fa-clock-o"></i> {{job.job_type}}</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="jobs_right">
                                    <div class="apply_now">
                                        <a class="heart_mark" href="#"> <i class="fa fa-heart"></i> </a>
                                        <a href="{% url 'job:job_detail' job.slug %}" class="boxed-btn3">Apply Now</a>
                                    </div>
                                    <div class="date">
                                        <p>Date line: {{job.published_at|date:'d M o'}}</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    
                    {% if jobs.has_other_pages %}    
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="pagination_wrap">
                                    <ul>
                                        
                                        {% if jobs.has_previous %}
                                            <li><a href="?page={{jobs.previous_page_number}}"> <i class="ti-angle-left"></i> </a></li>
                                        {% endif %}
                                        

                                        
                                        {% for i in jobs.paginator.page_range %}
                                            <li><a href="?page={{i}}"><span>{{i}}</span></a></li>   
                                        {% endfor %}
                                            
                                    
                                        {% if jobs.has_next %}
                                        <li><a href="?page={{jobs.next_page_number}}"> <i class="ti-angle-right"></i> </a></li>
                                        {% endif %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                    {% endif %}
                    
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock body %}

    


   