accounts/urls.py
from django.urls import path , include
from . import views

app_name='job'

urlpatterns = [
    path('signup',views.signup,name='signup'),
    path('profile',views.profile,name='profile'),
    path('profile/edit',views.profile_edit,name='profile_edit'),
]

job/urls.py
from django.urls import path , include
 
from . import views
from . import api 


app_name='job'

urlpatterns = [
    path('',views.job_list,name='job_list'),
    path('add',views.add_job,name='add_job'),
    path('<str:slug>',views.job_detail,name='job_detail'),
    # path('api/jobs',api.job_list_api,name='job_list_api'),
    # path('api/jobs/<int:id>',api.job_detail_api,name='job_detail_api'),
    
    #class based view 
    path('api/v2/jobs',api.JobListApi.as_view(),name='job_list_api'),
    path('api/v2/jobs/<int:id>',api.JobDetail.as_view(),name='jobDetail'),
    
]

project/urls.py
from argparse import Namespace
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
    path('jobs/',include('job.urls',namespace='jobs')),
    path('contact-us/',include('contact.urls',namespace='contacts')),
    # path('home/',include('home.urls',namespace='home')),
    path('api-auth/', include('rest_framework.urls'))
    
]

urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import User
from django.dispatch import receiver
from matplotlib import image

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    city = models.ForeignKey('City',related_name='user_city',on_delete=models.CASCADE,blank=True,null=True)
    phonenumber = models.CharField(max_length = 15)
    image = models.ImageField(upload_to='profile/')
    
    def __str__(self):
        return str(self.user)

@receiver(post_save,sender=User)
def create_user_profile(sender,instance,created,**kwargs):
    if created:
        Profile.objects.create(user=instance)


class City(models.Model):
    name = models.CharField(max_length=50)
    
    def __str__(self):
        return self.name

accounts/views.py
from audioop import reverse
from turtle import width
from django.shortcuts import redirect, render
from requests import request
from .form import ProfileForm, UserForm, signup_form
from django.contrib.auth import authenticate,login
from .models import Profile
# Create your views here.
def signup(request):
    
    if request.method == "POST":
        form = signup_form(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username,password=password)
            login(request,user)
            return redirect('/accounts/profile')
            
    else:
        form = signup_form()
    
    context={'form':form}
    return render(request,'registration/signup_form.html',context)


def profile(request):
    profile = Profile.objects.get(user=request.user)
    return render(request,'accounts/profile.html',{'profile':profile})


def profile_edit(request):
    profile = Profile.objects.get(user=request.user)
    
    if request.method == 'POST':
            userform = UserForm(request.POST,instance=request.user)
            profileform = ProfileForm(request.POST,request.FILES ,instance=profile)
            if userform.is_valid() and profileform.is_valid():
                userform.save()
                myprofile = profileform.save(commit=False)
                myprofile.user = request.user
                myprofile.save()
                return redirect('/accounts/profile')
                
    
    
    else:
        userform = UserForm(instance=request.user)
        profileform = ProfileForm(instance=profile)
    
    return render(request,'accounts/profile_edit.html',{'userform':userform,'profileform':profileform})

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% block body %}
        <!-- bradcam_area  -->
        
        <div class="bradcam_area bradcam_bg_1">
            <div class="container">
                <div class="row">
                    <div class="col-xl-12">
                        <div class="bradcam_text">
                            <h3></h3>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--/ bradcam_area  -->
    
        <div class="job_details_area">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 mx-auto">
                        <div class="job_sumary">
                            <div class="summery_header">
                                <h3>Profile Summery</h3>
                            </div>
                            <div class="job_content">
                                <ul>
                                    <li>Nam: <span>{{profile}}</span></li>
                                    <li>Email: <span>{{profile.user.email}} Position</span></li>
                                    <li>Phone: <span>{{profile.phonenumber}}</span></li>
                                    <li>Address: <span>{{profile.city}}</span></li>
                                </ul>
                                <a class="boxed-btn3 w-100"  href='{% url 'accounts:profile_edit' %}'>Edit Profile</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    
{%endblock body%} 

accounts/templates/accounts/profile_edit.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
        <!-- bradcam_area  -->
        
        <div class="bradcam_area bradcam_bg_1">
            <div class="container">
                <div class="row">
                    <div class="col-xl-12">
                        <div class="bradcam_text">
                            <h3>Edit Profile</h3>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--/ bradcam_area  -->
    
        <div class="job_details_area">
            <div class="container">
                <div class="row">
                    <div class="col-lg-10 mx-auto">
                    
                        <div class="apply_job_form white-bg">
                            <h4>Edit Profile</h4>
                            <form action="#" method = "POST" enctype="multipart/form-data">
                                {% csrf_token %}
                                {% bootstrap_form userform %}
                                {% bootstrap_form profileform %}
                                {% buttons %}
                                    <button class="boxed-btn3 w-100" type="submit">Edit</button>
                                {% endbuttons %}
                            
                            </form>
                        </div>
                    </div>
                    <div class="col-lg-4">
                    </div>
                </div>
            </div>
        </div>
    
{%endblock body%} 